config/routes.rb
Raven::Application.routes.draw do
  resources :books
  resources :artworks

  match "home" => "static_pages#home"
  match "help" => "static_pages#help"
  match "about" => "static_pages#about"

  devise_for :users

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'static_pages#home'
end

app/models/artwork.rb
# == Schema Information
#
# Table name: artworks
#
#  id           :integer          not null, primary key
#  yubikey      :string(255)
#  personal_msg :string(255)
#  work_number  :integer
#  signing_id   :integer
#  user_id      :integer
#  book_id      :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  signing_img  :string(255)      default("")
#

class Artwork < ActiveRecord::Base
  attr_accessible :yubikey, :yubi_otp, :work_number, :user_id, :book_id, :signing_img
  
  # this artwork belongs to a single user
  belongs_to :user
  
  # this artwork blongs to a single book.
  # Later we'll make this polymorphic.
  belongs_to :book
  accepts_nested_attributes_for :book
  
  # TBD: these cause problems in the create book then create artwork decision we are using.
  # validates :book_id, :presence => true
  # validates :work_number, :numericality => { :only_integer => true } 
  
  ###########
  # Yubikey methods. Here for now, since we do not use yubikeys anywhere but Artwork.
  # Yubikeys have 32 chars of encrypted data, and 0..48 ModHex chars total. So a valid-looking
  # yubikey will have a length of 32..48, with the first 0..16 chars being the fixed ID.
  # For the moment, we are using 12 char IDs which implies 44 char yubi_otp.
  
  # yubi_otp is a virtual asset. We only need the fixed characters to store in the yubikey.
  # yubi_valid determines if the OTP is valid.
  
  def yubi_otp=(yubi)
    self.yubikey = yubi[0..11]
  end
  
  def yubi_otp
    yubikey
  end
  
  # yubi_ish? tells if the pattern might be a yubi_otp
  
  def self.yubi_ish?(pattern)
    pattern.length == 44 ? true : false
  end
  
  # otp.replayed? will tell if there is a replay
  
  def self.yubi_valid?(yubiotp)
    begin
      otp = Yubikey::OTP::Verify.new(yubiotp)
      logger.debug("Yubi_valid: #{otp.valid?} and #{yubiotp}")

      otp.valid?
    rescue Yubikey::OTP::InvalidOTPError
      logger.debug("Yubi_valid: InvalidOTPError")
      false
    end
  end
  
  def self.find_by_yubi(key)
    where(:yubikey => key[0..11])
  end
 
  # end of Yubikey methods
  ###########
  
  def self.my_collection(user)
    where(:user_id => user.id)
  end
  
  # The search function looks for artwork with a yubikey match or the search term in title or author
  # TBD - just uses one term.
  
  def self.search(params)
    
    unless params.has_key?(:search)
      return Artwork.all
    end
    
    if Artwork.yubi_ish? params[:search]
        art = Artwork.find_by_yubi params[:search][0..11]
        return [art] unless art.empty?
    end

    # either we didn't find any book with the yubikey, or we have a non-yubi pattern
    
    q = "%#{params[:search]}%"
    Artwork.where("book.title LIKE ? OR book.author LIKE ?", q, q)
  end
end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
  # GET /artworks
  # GET /artworks.json
  def index
    @artworks = Artwork.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @artworks }
    end
  end

  # GET /artworks/1
  # GET /artworks/1.json
  def show
    @artwork = Artwork.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @artwork }
    end
  end

  # GET /artworks/new
  # GET /artworks/new.json
  # TBD: rethink how this operation works.
  def new
    @artwork = Artwork.new
    @artwork.build_book

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @artwork }
    end
  end

  # GET /artworks/1/edit
  def edit
    @artwork = Artwork.find(params[:id])
  end

  # POST /arts
  # POST /arts.json
  def create
    @artwork = Artwork.new(params[:artwork])
    
    # somehow we must create the additional artwork objects for the edition.

    respond_to do |format|
      if @artwork.save
        format.html { redirect_to @artwork, :notice => 'Art was successfully created.' }
        format.json { render :json => @artwork, :status => :created, :location => @artwork }
      else
        format.html { render :action => "new" }
        format.json { render :json => @artwork.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /artworks/1
  # PUT /artworks/1.json
  def update
    @artwork = Artwork.find(params[:id])

    respond_to do |format|
      if @artwork.update_attributes(params[:artwork])
        format.html { redirect_to @artwork, notice => 'Art was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @artwork.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /artworks/1
  # DELETE /artworks/1.json
  def destroy
    @artwork = Artwork.find(params[:id])
    @artwork.destroy

    respond_to do |format|
      format.html { redirect_to artworks_url }
      format.json { head :no_content }
    end
  end
  
  #
  # search - you can type an author, a title, or a yubi_otp in the search field
  #
  
  def search
    if yubi_valid?(params[:search_string])
      @yubi_valid = true
      @artwork = Art.yubi_find(params[:search_string])
    elsif title_valid?(params[:search_string])
      @artwork = Art.title_find(params[:search_string])
    else
      @artwork = Art.author_find(params[:search_string])
    end
    
    render show
  end
end

app/helpers/artworks_helper.rb
module ArtworksHelper
end

app/views/artworks/_arttable.html.erb
<table class="table table-striped table-condensed">
  <% if artlist.empty? %>
    <h2>No Art objects found</h2>
  <% else %>
    <thead>
      <tr>
        <th></th>
        <th>Owner</th>
        <th>Title</th>
        <th>Work number</th>
        <th>Signature</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% artlist.each do |art| %>
      <tr>
        <td><% if !art.yubikey.blank? %><span class="label label-info">Verifiable</span><% end %></td>
        <td><%= art.user ? art.user.full_name : "Available" %></td>
        <td><%= art.book.title %></td>
        <% if art.book.edition_size > 1 %>
          <td><%= art.work_number %> of <%= art.book.edition_size %></td>
        <% else %>
          <td><em>Unique work</em></td>
        <% end %>
        <td><% if art.signing_img.empty? %><em>unsigned</em>
					  <% else %><a href=<%= "http://i17.tinypic.com/#{art.signing_img}.jpg" %> rel="prettyPhoto">signature</a>  <!-- <%= image_tag(art.signing_img + "_t") %> -->
						<% end %>
				</td>
        <div class="btn-group">
          <td><%= link_to 'Show', art, :class => "btn" %></td>
          <td><%= link_to 'Edit', edit_artwork_path(art), :class => "btn" %></td>
        </div>
        <td><%= link_to 'Destroy', art, :method => :delete, :data => { confirm: 'Are you sure?' }, :class => "btn btn-danger" %></td>
      </tr>
      <% end %>
    </tbody>
  <% end %>
</table>

app/views/artworks/_form.html.erb
<%= simple_form_for(@artwork) do |f| %>
  <% if @artwork.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@art.errors.count, "error") %> prohibited this art from being saved:</h2>

      <ul>
      <% @art.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :yubi_otp, :as => :string %>
  <%= f.input :work_number %>
  <fieldset class="admin_edit"><legend>Admin use only</legend>
  <%= f.association :user, :label => "Owner", :label_method => :full_name %>
  <%= f.association :book %>
	<%= f.input :signing_img %>
  </fieldset>
  <%= f.button :submit, :class => "btn btn-primary" %>
<% end %>

app/views/artworks/edit.html.erb
<h2><%= @artwork.book.title %></h2>

<%= render 'form' %>

<%= link_to 'Show', @artwork %> | <%= link_to 'Back', artworks_path %>

app/views/artworks/index.html.erb
<h1>Listing artworks</h1>

<%= render :partial => "arttable", :locals => { :artlist => @artworks } %>
<br />

<%= link_to 'New Art', new_artwork_path %>

app/views/artworks/new.html.erb
<h2>Add a new Artwork limited edition <em>rethink</em></h2>

<%= simple_form_for(@artwork) do |f| %>
  <% if @artwork.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artwork.errors.count, "error") %> prohibited this artwork from being saved:</h2>

      <ul>
      <% @artwork.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :yubi_otp, :hint => "optional" %>

  <h3>Create the limited edition description</h3>
  <div class="book">
    <%= f.simple_fields_for :book do |book| %>
      <%= book.input :title, :required => true %>
      <%= book.input :author, :required => true %>
      <%= book.input :image, :hint => "filename" %>
    <% end %>
  </div>
  <%= f.submit :class => "btn btn-primary" %>
<% end %>

<%= link_to 'Back', artworks_path %>

app/views/artworks/show.html.erb
<p id="notice"><%= notice %></p>

<% if @artwork.nil? %>
  <h3>No artwork found</h3>
<% else %>
  <h2>Ownership record</h2>
  <% if admin_user? %>
    <p>
      <b>Yubikey: </b>
      <% if @artwork.yubikey && @artwork.yubikey.size %>
        <%= @artwork.yubikey %>
      <% else %>
        <quiet>Unassigned</quiet>
      <% end %>
    </p>
  <% end %>
  
  <% if !@yubi_valid.nil? %>
    <p><span class="label label-success">Verified</span></p>
  <% elsif @artwork.yubikey && @artwork.yubikey.size %>
    <p><span class="label label-info">Verifiable</span></p>
  <% end %>

  <p>
    <b>Owner: </b><%= @artwork.user_id ? @artwork.user.full_name : 'Available' %> <quiet>(<%= @artwork.user_id.nil? ? 'nil' :  @artwork.user_id %>)</quiet>
  </p>

  <p>
    <b>Book: </b><%= @artwork.book.title %>
  </p>

  <p>
    <% if @artwork.book.edition_size > 1 %>
      <b><%= @artwork.work_number %></b> of <%= @artwork.book.edition_size %>
    <% else %>
      <b>Original work</b>
    <% end %>
  </p>

	<p><% if @artwork.signing_img.empty? %>no signature<% else %>
		 <a href=<%= "http://flickr.com/photos/#{@artwork.signing_img}" %> rel="prettyPhoto">signature</a><% end %>
	</p>
<% end %>

<%= link_to 'Edit', edit_artwork_path(@artwork) %> | <%= link_to 'Back', artworks_path %>