config/routes.rb
Raven::Application.routes.draw do
  resources :books
  resources :artworks

  match "home" => "static_pages#home"
  match "help" => "static_pages#help"
  match "about" => "static_pages#about"

  devise_for :users

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'static_pages#home'
end

app/views/layouts/_footer.html.erb
<footer>
	<div>
		<center><quiet>Copyright &copy; GCCS 2012</quiet></center>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<nav class="navbar-inner">
    <div class="container">
			<%= image_tag "raven_icon40.png" %>
			<%= link_to "Raven", root_path, :class => 'brand' %>
			<ul class = "nav pull-right">
				<li><%= link_to(home_path) do %><i class="icon-home icon-white"></i> Home<% end %></li>
				<li><%= link_to('About', about_path) %></li>
				<li><%= link_to(help_path) do %><i class="icon-question-sign icon-white"></i> Help<% end %></li>
			  <% if user_signed_in? %>
			    <li><%= link_to(destroy_user_session_path, :method=>'delete') do %><i class="icon-user icon-white"></i> Logout<% end %></li>
			  <% else %>
			    <li><%= link_to(new_user_session_path) do %><i class="icon-user icon-white"></i> Login<% end %></li>
			  <% end %>
			  <% if user_signed_in? %>
			    <li><%= link_to(edit_user_registration_path) do %><i class="icon-cog icon-white"></i> Edit account<% end %></li>
			  <% else %>
			    <li><%= link_to('Sign up', new_user_registration_path) %></li>
			  <% end %>
			</ul>
		</div>
	</nav>
</header>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">&#215;</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- 'Font Awesome - http://fortawesome.github.com/Font-Awesome' -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Raven" %></title>
    <meta name="description" content="Raven application">
    <meta name="author" content="John F. Nixon">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <%= render 'layouts/header' %>

    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div> <!-- end of row -->
        </div> <!-- end of content -->

			  <%= render 'layouts/footer' %>
			</div> <!-- end of container -->
		</div> <!--! end of #main -->
		<!-- UserVoice generated feedback tab -->
		<script type="text/javascript">
		  var uvOptions = {};
		  (function() {
		    var uv = document.createElement('script'); uv.type = 'text/javascript'; uv.async = true;
		    uv.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'widget.uservoice.com/INrqR7cBCINX2aEM3bDHjw.js';
		    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(uv, s);
		  })();
		</script>
		<!-- end UserVoice tab -->cp
	</body>
</html>